projects:
  default:
    schema: ./graphql/schema.graphql
    include: ./plugins/*/graphql/**/*.graphql
    extensions:
      endpoints:
        ReactiveGraph@http:
          url: http://localhost:31415/graphql
          introspect: true
        ReactiveGraph@https:
          url: https://localhost:31415/graphql
          introspect: true
  dynamicGraph:
    schema: ./dynamic_graph/schema.graphql
    include: ./plugins/*/dynamic_graph/**/*.graphql
    extensions:
      endpoints:
        DynamicGraph@http:
          url: http://localhost:31415/dynamic_graph
          introspect: true
        DynamicGraph@https:
          url: https://localhost:31415/dynamic_graph
          introspect: true
