[target.aarch64-unknown-linux-gnu]
objcopy = { path ="aarch64-linux-gnu-objcopy" }
strip = { path ="aarch64-linux-gnu-strip" }
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
objcopy = { path ="arm-none-eabi-objcopy" }
strip = { path ="arm-none-eabi-strip" }
linker = "arm-linux-gnueabihf-gcc"
