name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - "plugins/*/crates/**/*.rs"
      - "plugins/*/crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "plugins/*/crates/*/*.rs"
      - "plugins/*/crates/*/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/docs.yml"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  RUSTDOCFLAGS: --enable-index-page -Zunstable-options

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-22.04
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-03-14
          components: rustfmt, rust-src
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Yarn
        uses: borales/actions-yarn@v5
        with:
          cmd: --cwd plugins/graphql-client/web install
      - name: Install Yarn
        uses: borales/actions-yarn@v5
        with:
          cmd: --cwd plugins/graphql-schema-visualization/web install
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run cargo doc
        run: cargo doc --all --no-deps
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: docs
          cname: tooling.reactive-graph.io
          # keep_files: true
